alter table public.segments
  add column if not exists guest_role text,
  add column if not exists extraction_confidence numeric check (extraction_confidence between 0 and 1),
  add column if not exists source_excerpt text;

insert into public.programs (id, name, short_name, hosts, managed, active) values
  ('rotativa-campo', 'La Rotativa del Campo', 'Rotativa del Campo', 'Jesús Miguel Calderón', false, true),
  ('rotativa-am', 'La Rotativa del Aire | Edición Mañana', 'Rotativa AM', 'Carlos Villarreal y Joanna Castro', true, true),
  ('ampliacion-lima', 'Ampliación de noticias Lima', 'Ampliación Lima', 'Mávila Huertas y Fernando Carvallo', true, true),
  ('ampliacion-regional', 'Ampliación de noticias regional', 'Ampliación regional', 'Edición regional', true, true),
  ('encendidos', 'Encendidos', 'Encendidos', 'Sara Abu Sabbah y Carlos Galdós', true, true),
  ('rotativa-tarde', 'La Rotativa del Aire | Edición Tarde', 'Rotativa Tarde', 'Carlos Villarreal y Joanna Castro', true, true),
  ('futbol-cancha', 'Fútbol como cancha', 'Fútbol como cancha', 'Jesús Arias y Alan Diez', false, true),
  ('chistosos', 'Los Chistosos', 'Los Chistosos', 'Hernán Vidaurre y Daniel Marquina', true, true),
  ('espacio-vital', 'Espacio Vital', 'Espacio Vital', 'Elmer Huerta', false, true),
  ('conexion', 'Conexión', 'Conexión', 'Martín Riepl y Fátima Chávez', true, true),
  ('rotativa-noche', 'La Rotativa del Aire | Edición Noche', 'Rotativa Noche', 'Jesús Miguel Calderón', true, true),
  ('vamos-var', 'Vamos al VAR', 'Vamos al VAR', 'Jesús Arias, Alan Diez y Pedro García', false, true),
  ('sabelones', 'Sabelones', 'Sabelones', 'Daniel Marquina', false, true),
  ('las-cosas', 'Las cosas como son', 'Las cosas como son', 'Equipo por confirmar', true, true),
  ('prueba-fuego', 'Prueba de fuego', 'Prueba de fuego', 'Equipo por confirmar', true, true),
  ('asi-somos', 'Así somos', 'Así somos', 'Equipo por confirmar', true, true),
  ('lo-mejor-campo', 'Lo mejor de la semana de La Rotativa del Campo', 'Lo mejor de Rotativa del Campo', 'Especial semanal', false, true),
  ('rotativa-sat-am', 'La Rotativa de fin de Semana | Sábado', 'Rotativa AM Sábado', 'Fátima Chávez y César Espinoza', true, true),
  ('ampliacion-sat', 'Ampliación de Noticias | Sábado', 'Ampliación Sábado', 'Fernando Vivas y César Espinoza', true, true),
  ('enfoque-sat', 'Enfoque de los sábados', 'Enfoque de los sábados', 'Fernando Carvallo', false, true),
  ('dialogo-fe', 'Diálogo de Fe', 'Diálogo de Fe', 'Fernando Carvallo y Carlos Castillo', true, true),
  ('sencillo-bolsillo', 'Sencillo y al Bolsillo', 'Sencillo y al Bolsillo', 'Equipo del programa', true, true),
  ('en-escena', 'En escena', 'En escena', 'Johnny Padilla', true, true),
  ('chistosos-best', 'Lo mejor de Los Chistosos', 'Lo mejor de Los Chistosos', 'Hernán Vidaurre y Daniel Marquina', false, true),
  ('letras-tiempo', 'Letras en el tiempo', 'Letras en el tiempo', 'Patricia del Río', false, true),
  ('ampliacion-sat-repeat', 'Ampliación de Noticias | Sábado | Repetición', 'Ampliación Sábado | Repetición', 'Repetición', false, true),
  ('en-escena-repeat', 'En Escena | Repetición', 'En Escena | Repetición', 'Repetición', false, true),
  ('rotativa-sat-pm', 'La Rotativa del Aire | Sábado Noche', 'Rotativa PM Sábado', 'Fin de semana', true, true),
  ('enfoque-sat-repeat', 'Enfoque de los Sábados | Repetición', 'Enfoque | Repetición', 'Repetición', false, true),
  ('letras-repeat', 'Letras en el tiempo | Repetición', 'Letras | Repetición', 'Repetición', false, true),
  ('rpp-informando', 'RPP Informando | Domingo', 'RPP Informando', 'Carlos Montalvo', false, true),
  ('rotativa-sun-am', 'La Rotativa de fin de Semana | Domingo', 'Rotativa AM Domingo', 'Carlos Villarreal y Noemy Mamani', true, true),
  ('ampliacion-sun', 'Ampliación de Noticias | Domingo', 'Ampliación Domingo', 'Fernando Vivas y Carlos Villarreal', true, true),
  ('domingo-fiesta', 'Domingo es fiesta', 'Domingo es fiesta', 'Jorge Rodríguez', true, true),
  ('siempre-casa', 'Siempre en Casa', 'Siempre en Casa', 'Jorge Rodríguez', true, true),
  ('rotativa-sun-pm', 'La Rotativa del Aire | Domingo Noche', 'Rotativa PM Domingo', 'Fin de semana', true, true),
  ('ampliacion-sun-repeat', 'Ampliación de Noticias | Domingo | Repetición', 'Ampliación Domingo | Repetición', 'Repetición', false, true)
on conflict (id) do update set
  name = excluded.name,
  short_name = excluded.short_name,
  hosts = excluded.hosts,
  managed = excluded.managed,
  active = excluded.active;
